;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cofi/maybe-exit
	evil-append-line
	evil-change
	evil-delete
	evil-delete-char
	evil-find-char
	evil-force-normal-state
	evil-insert
	evil-next-line
	evil-normal-state
	evil-previous-line
	evil-search-next
	))

(setq mc/cmds-to-run-once
      '(
	))
